name: Generate ASCII Artwork

on: push

jobs:
    ascci_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay Package
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON." >> dragon.txt     
        
        - name: Sleep 5 sec
          run: sleep 5

        - name: Test file exists
          run: grep -i dragon dragon.txt

        - name: Read file
          run: cat dragon.txt

        - name: List and Read files
          run: ls -ltra

