name: Shell Script Test Workflow

on: push

jobs:
    shell_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: List the files
          run: ls -ltra

        - name: Executing Shell Script
          run: ./cowsay.sh

