name: Shell Script Workflow test

on: workflow_dispatch

jobs:
  shell_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: List files
      run: ls -ltra

    # - name: Change script permission 
    #   run: chmod +x ./cowsay.sh

    - name: Executing Shell Script
      run: |
        chmod +x ./cowsay.sh
        ./cowsay.sh

