name: Exploring enviornment variable
# wokflow lavel variable for all Jobs within single workflow
env:
  WORKF_VAR: workf-var

on: workflow_dispatch

jobs:
  build:
    # 
    env:
      JOB1_VAR: job1-var
    runs-on: ubuntu-latest
    steps:
    - name: Step1 Variables
      env:
        STEP1_VAR: step1-var
      run: echo $STEP1_VAR 

    - name: Step2 Variables
      env:
        STEP2_VAR: step2-var
      run: echo ${{ env.STEP2_VAR }}

    - name: Job Variables
      run: echo ${{ env.JOB1_VAR }}

    - name: Workflow variables in Job1
      run: echo ${{ env.WORKF_VAR }} in job1 is ${{ env.WORKF_VAR }}
    
    - name: Repository Secret
      run: echo Secret from repo is ${{ secrets.REPO_SECRET }}
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: prod-deployment 
      cancel-in-progress: true 
    # if cancel-in-progress:false then existing running jobs will not cancel but new one will wait for current job to get completed.
    timeout-minutes: 1
    # timeout-minutes: 1 will cancel the any jobs running morethan 1 min
    steps:
    - name: Workflow variables in Job2
      run: echo ${{ env.WORKF_VAR }} in job2 is ${{env.WORKF_VAR}}

    - name: Repository Variable
      run: echo Repository variable is ${{ vars.REPO_VAR }}

    - name: Sleep for 5 min
      run: sleep 300s
