name: My first workflow

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Welcome message
        run: echo "my first github action job1"

      - name: List files
        run: ls

      - name: Read file
        run: cat README.md