name: Matrix Configuration Workflow

on:
#  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
#  deploy-on-ubuntu:
    runs-on: ${{ matrix.os}}
    steps:
    - name: Echo Docker Detaails
      run: docker info
    - name: Run Image ${{ matrix.images }}
      run: docker run ${{ matrix.images }}

  ## Below Jobs will be taken care by matrix strategy as coded above

  # deploy-on-window:
  #   runs-on: windows-latest
  #   needs: deploy-on-ubuntu
  #   steps:
  #   - name: Echo Docker Detaails
  #     run: docker info
  #   - name: Run Image
  #     run: docker run hello-world      

