name: Generate ASCII Artwork - Multi Jobs

on: workflow_dispatch

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Cowsay Package
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON." >> dragon.txt     

    - name: List files 
      run: ls -ltr
      
    - name: Upload the Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cowsay-artifact
        path: dragon.txt
  
  test_job_1:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download the Artifact
      uses: actions/download-artifact@v4
      with:
        name: cowsay-artifact

    - name: Test file exists
      run: grep -i dragon dragon.txt

    - name: List files 
      run: ls -ltr

  deploy_job_1:
    needs: [test_job_1]
    runs-on: ubuntu-latest
    steps:
    - name: Download the Artifact
      uses: actions/download-artifact@v4
      with:
        name: cowsay-artifact

    - name: Read files
      run: |
          cat dragon.txt   
    
    - name: List and Read files
      run: ls -ltra